name: desenvolvimento_flutter_modulo_01
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0  
  geolocator: ^8.0.1
  location: ^4.4.0
  provider: ^6.0.5
  firebase_core: ^2.13.1
  image_picker: ^1.0.0
  firebase_auth: ^4.6.3
  path_provider: ^2.0.5
  calculadora_pk: 
    git:
      url: https://github.com/RodrigoAugusto31/calculadora_pk.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
